# Generated by Django 5.1.4 on 2025-01-17 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_scorecard"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorecard",
            name="scored_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scorecards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
