# Generated by Django 5.1.4 on 2025-01-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_scorecard_scored_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorecard",
            name="score",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
