# Generated by Django 5.1.4 on 2025-01-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_scorecard_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorecard",
            name="score",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
